name: Pester Unit Tests
on:
  push:
jobs:
  test-pwsh-v7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Pester tests (PowerShell v7)
      run: |
        Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
        Set-PSRepository psgallery -InstallationPolicy trusted
        Install-Module -Name Pester -RequiredVersion 5.5.0 -Confirm:$false -Force
        $credential = New-Object System.Management.Automation.PSCredential("${{ secrets.OP_UNAME }}", ("${{ secrets.OP_PASS }}" | ConvertTo-SecureString -AsPlainText -Force)) 
        ./Tests/OpenProvider.tests.ps1 -Credential $credential -Verbose
        if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') {exit 1}
      shell: pwsh
