name: Publish module to PowerShellGallery
on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: "OpenProviderPowerShell"
    - name: Publish Module
      uses: pcgeek86/publish-powershell-module-action@v20
      with:
        NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
